import type { SkillId } from '../skills'
import type { TimeWindow } from '../time'
import { NIGHT_WINDOW, hours } from '../time'
import type { Availability } from './availability'
import { BIG_PLACES, TOWNS } from './availability'
import type { Requirements } from './jobs'

export interface CourseDef {
  readonly id: string
  readonly label: string
  readonly description: string
  readonly skill: SkillId
  readonly durationMinutes: number
  /** Плата наставнику — единственный обязательный сток денег в срезе 1. */
  readonly cost: number
  /** Сырой опыт за занятие: заметно больше, чем даёт смена на работе. */
  readonly xp: number
  /** Выше своего уровня наставник не научит. */
  readonly teacherCap: number
  readonly fatigue: number
  readonly requires?: Requirements
  /** Часы, в которые дело можно начать. По умолчанию — дневные. */
  readonly window?: TimeWindow
  /** Где это вообще бывает. Без указания — везде. */
  readonly where?: Availability
}

export const COURSES: readonly CourseDef[] = [
  {
    id: 'lettersBasics',
    where: { archetypes: ['town', 'city', 'capital', 'monastery'] },
    label: 'Уроки грамоты',
    description: 'Писец берёт учеников по утрам. Читать, писать, считать долги.',
    skill: 'scholarship',
    durationMinutes: hours(4),
    cost: 6,
    xp: 70,
    teacherCap: 25,
    fatigue: 8,
  },
  {
    id: 'swordDrill',
    where: { archetypes: ['town', 'city', 'capital', 'fortress'] },
    label: 'Занятия с мечом',
    description: 'Отставной наёмник гоняет по кругу во дворе. Синяки в стоимость входят.',
    skill: 'lightWeapons',
    durationMinutes: hours(3),
    cost: 8,
    xp: 65,
    teacherCap: 30,
    fatigue: 25,
  },
  {
    id: 'meditation',
    where: { archetypes: ['monastery', 'city', 'capital'] },
    label: 'Дыхание и сосредоточение',
    description: 'Скучно, дорого и без видимого результата. Без этого магия не даётся.',
    skill: 'concentration',
    durationMinutes: hours(3),
    cost: 5,
    xp: 60,
    teacherCap: 25,
    fatigue: 5,
  },
  {
    id: 'streetCharms',
    where: { archetypes: ['village', 'town', 'port'] },
    label: 'Наговоры за медяки',
    description:
      'Полоумная старуха с окраины берёт дёшево и учит опасно. Школа такого не признаёт.',
    skill: 'magic',
    durationMinutes: hours(3),
    cost: 3,
    xp: 45,
    teacherCap: 12,
    fatigue: 15,
    // Улица выводит на таких людей; выросшему при дворе их просто не покажут.
    requires: { tags: ['street_smart'] },
  },
  {
    id: 'magicIntro',
    where: { archetypes: ['capital', 'city'] },
    label: 'Школа магии: вводный курс',
    description: 'За стенами школы учат тому, за что на улице сожгли бы.',
    skill: 'magic',
    durationMinutes: hours(6),
    cost: 20,
    xp: 85,
    teacherCap: 30,
    fatigue: 20,
    requires: { skills: { scholarship: 8, concentration: 5 } },
  },
  {
    id: 'archeryRange',
    where: { archetypes: ['fortress', 'town', 'city', 'capital'] },
    label: 'Стрельбище у стены',
    description: 'Сотня выстрелов в день и мозоли, которые потом уже не сойдут.',
    skill: 'archery',
    durationMinutes: hours(3),
    cost: 7,
    xp: 60,
    teacherCap: 30,
    fatigue: 20,
  },
  {
    id: 'ridingSchool',
    where: { archetypes: ['town', 'city', 'capital'] },
    label: 'Выездка',
    description: 'Конюший берёт за час столько, сколько конюх получает за день.',
    skill: 'riding',
    durationMinutes: hours(3),
    cost: 10,
    xp: 60,
    teacherCap: 30,
    fatigue: 18,
  },
  {
    id: 'shopApprentice',
    where: { archetypes: TOWNS },
    label: 'При лавке',
    description: 'Хозяин показывает, где в счёте прячется прибыль, и берёт за это долю.',
    skill: 'trade',
    durationMinutes: hours(4),
    cost: 12,
    xp: 70,
    teacherCap: 30,
    fatigue: 10,
  },
  {
    id: 'bonesetter',
    where: { archetypes: ['town', 'city', 'capital', 'monastery'] },
    label: 'У костоправа',
    description: 'Кровь, крик и руки, которые перестают дрожать к третьему разу.',
    skill: 'healing',
    durationMinutes: hours(4),
    cost: 9,
    xp: 65,
    teacherCap: 30,
    fatigue: 15,
  },
  {
    id: 'lawAndNumbers',
    where: { archetypes: BIG_PLACES },
    label: 'Законы и счёт',
    description: 'Городской стряпчий берёт дорого и смотрит на тебя как на мебель.',
    skill: 'scholarship',
    durationMinutes: hours(5),
    cost: 18,
    xp: 130,
    teacherCap: 45,
    fatigue: 10,
    requires: { skills: { scholarship: 15 } },
  },
  {
    id: 'bladeMaster',
    where: { archetypes: BIG_PLACES },
    label: 'Мастер клинка',
    description: 'Берёт только тех, кто уже умеет. Учит тому, что убивает, а не тому, что красиво.',
    skill: 'lightWeapons',
    durationMinutes: hours(4),
    cost: 28,
    xp: 150,
    teacherCap: 55,
    fatigue: 35,
    requires: { skills: { lightWeapons: 20 } },
  },
  {
    id: 'magicAdeptCourse',
    where: { archetypes: ['capital'] },
    label: 'Школа магии: курс адепта',
    description: 'Настоящее обучение начинается здесь — и стоит настоящих денег.',
    skill: 'magic',
    durationMinutes: hours(7),
    cost: 55,
    xp: 175,
    teacherCap: 55,
    fatigue: 30,
    window: { fromHour: 8, toHour: 16 },
    requires: { skills: { magic: 14, concentration: 10 } },
  },

  // --- школа (этап 40): дальше адепта учат годы и деньги -----------------------
  {
    id: 'magicJourneymanCourse',
    where: { archetypes: ['capital', 'city'], school: 'magister' },
    label: 'Школа магии: курс подмастерья',
    description:
      'Полгода при школе сжаты в недели занятий. Дорого, долго и без этого дальше не пускают.',
    skill: 'magic',
    durationMinutes: hours(24 * 5),
    cost: 260,
    xp: 900,
    teacherCap: 72,
    fatigue: 70,
    window: { fromHour: 8, toHour: 12 },
    requires: { skills: { magic: 30, concentration: 20 } },
  },
  {
    id: 'magicMasterCourse',
    where: { archetypes: ['capital'], school: 'archmage' },
    label: 'Академия: наставничество архимага',
    description:
      'Архимаг берёт учеников редко и берёт за это как за дом. Зато ведёт до самого верха.',
    skill: 'magic',
    durationMinutes: hours(24 * 10),
    cost: 900,
    xp: 1800,
    teacherCap: 92,
    fatigue: 90,
    window: { fromHour: 8, toHour: 12 },
    requires: { skills: { magic: 55, concentration: 40 } },
  },

  // --- вторая дюжина: чтобы ни один навык не рос «только в столице» ----------
  {
    id: 'axeYard',
    where: { archetypes: ['fortress', 'mine', 'town'] },
    label: 'Двор тяжёлого оружия',
    description: 'Отставной десятник учит бить топором и булавой. Щиты казённые, синяки свои.',
    skill: 'heavyWeapons',
    durationMinutes: hours(3),
    cost: 9,
    xp: 65,
    teacherCap: 30,
    fatigue: 28,
  },
  {
    id: 'porterGuild',
    where: { archetypes: TOWNS },
    label: 'Артель грузчиков',
    description: 'Старшина показывает, как поднимать, чтобы спина дожила до сорока.',
    skill: 'hardLabour',
    durationMinutes: hours(3),
    cost: 4,
    xp: 55,
    teacherCap: 25,
    fatigue: 25,
  },
  {
    id: 'cutpurseSchool',
    where: { archetypes: ['city', 'port'], minPopulation: 2000 },
    label: 'Наука ловких рук',
    description: 'Старый вор берёт учеников в задней комнате корчмы. Не спрашивай, где он сидел.',
    skill: 'sleight',
    durationMinutes: hours(3),
    cost: 12,
    xp: 70,
    teacherCap: 35,
    fatigue: 10,
    window: NIGHT_WINDOW,
  },
  {
    id: 'runnersTrack',
    where: { archetypes: ['town', 'city', 'capital', 'fortress'] },
    label: 'Беговая дорожка стражи',
    description: 'Круг за кругом с мешком песка на спине. Сотник считает круги, ты — минуты.',
    skill: 'athletics',
    durationMinutes: hours(2),
    cost: 5,
    xp: 55,
    teacherCap: 30,
    fatigue: 30,
  },
  {
    id: 'trapperLore',
    where: {
      archetypes: ['village', 'mine', 'monastery'],
      terrains: ['forest', 'hills', 'mountains', 'marsh'],
    },
    label: 'Наука следопыта',
    description: 'Старый охотник учит читать лес: где ночевать, что есть, куда не ходить.',
    skill: 'survival',
    durationMinutes: hours(5),
    cost: 6,
    xp: 70,
    teacherCap: 35,
    fatigue: 20,
  },
  {
    id: 'masonsLodge',
    where: { archetypes: ['city', 'capital', 'mine', 'fortress'] },
    label: 'Ложа каменщиков',
    description: 'Арки, подпорки и подкопы. Мастер рисует мелом на полу и требует повторить.',
    skill: 'engineering',
    durationMinutes: hours(4),
    cost: 14,
    xp: 80,
    teacherCap: 40,
    fatigue: 15,
    requires: { skills: { scholarship: 5 } },
  },
  {
    id: 'ascetic',
    where: { archetypes: ['monastery'] },
    label: 'Пост и бдение',
    description: 'Сутки без еды и сна под присмотром брата-настоятеля. Учит терпеть.',
    skill: 'fortitude',
    durationMinutes: hours(8),
    cost: 3,
    xp: 75,
    teacherCap: 35,
    fatigue: 40,
  },
  {
    id: 'rhetoric',
    where: { archetypes: ['city', 'capital', 'monastery'] },
    label: 'Риторика',
    description: 'Как говорить, чтобы слушали, и как молчать, чтобы верили. Учит бывший стряпчий.',
    skill: 'persuasion',
    durationMinutes: hours(3),
    cost: 12,
    xp: 70,
    teacherCap: 40,
    fatigue: 8,
    requires: { skills: { scholarship: 4 } },
  },
  {
    id: 'sergeantsSchool',
    where: { archetypes: ['fortress', 'capital'] },
    label: 'Школа десятников',
    description: 'Строй, шаг, команда. Сержант орёт, пока строй не станет строем.',
    skill: 'command',
    durationMinutes: hours(4),
    cost: 15,
    xp: 80,
    teacherCap: 40,
    fatigue: 22,
    requires: { skills: { heavyWeapons: 4 } },
  },
  {
    id: 'horseArchery',
    where: { archetypes: ['village', 'town'], terrains: ['steppe', 'plains'] },
    label: 'Стрельба с седла',
    description: 'Степняк учит пускать стрелу на скаку. Сначала — не падать.',
    skill: 'archery',
    durationMinutes: hours(4),
    cost: 10,
    xp: 85,
    teacherCap: 45,
    fatigue: 25,
    requires: { skills: { riding: 8, archery: 6 } },
  },
  {
    id: 'guildAccounts',
    where: { archetypes: ['city', 'capital', 'port'], minPopulation: 2500 },
    label: 'Счётная палата гильдии',
    description: 'Векселя, курсы и то, как не разориться на разнице. Учат за долю.',
    skill: 'trade',
    durationMinutes: hours(4),
    cost: 30,
    xp: 140,
    teacherCap: 55,
    fatigue: 10,
    requires: { skills: { trade: 15, scholarship: 8 } },
  },
  {
    id: 'surgeon',
    where: { archetypes: ['capital', 'city'], minPopulation: 3000 },
    label: 'Хирург при лечебнице',
    description: 'Пила, нитки и спирт. Берёт тех, кто уже умеет останавливать кровь.',
    skill: 'healing',
    durationMinutes: hours(5),
    cost: 32,
    xp: 150,
    teacherCap: 55,
    fatigue: 25,
    requires: { skills: { healing: 15 } },
  },
]

export const COURSES_BY_ID: Readonly<Record<string, CourseDef>> = Object.fromEntries(
  COURSES.map((course) => [course.id, course]),
)
