import type { SkillId } from '../skills'
import type { TimeWindow } from '../time'
import { NIGHT_WINDOW, hours } from '../time'
import type { Availability } from './availability'
import { TOWNS } from './availability'

/** Требования к персонажу: минимальные уровни навыков и обязательные теги. */
export interface Requirements {
  readonly skills?: Partial<Record<SkillId, number>>
  readonly tags?: readonly string[]
}

export interface JobDef {
  readonly id: string
  readonly label: string
  readonly description: string
  readonly durationMinutes: number
  /** Плата за смену. Единственный источник денег в срезе 1. */
  readonly pay: number
  /** Сколько сырого опыта получает каждый задействованный навык. */
  readonly practice: Partial<Record<SkillId, number>>
  readonly fatigue: number
  readonly requires?: Requirements
  /** Часы, в которые дело можно начать. По умолчанию — дневные. */
  readonly window?: TimeWindow
  /** Где это вообще бывает. Без указания — везде. */
  readonly where?: Availability
  /**
   * Работа, на которую берут всех (этап 67, Я1).
   *
   * Сев, жатва и зимняя подёнщина не спрашивают, кто ты и любит ли тебя
   * хозяин: руки нужны сейчас. У прочих работ в поселении есть хозяин, и он
   * может прогнать (этап 50).
   */
  readonly openHands?: boolean
}

/**
 * Подработки первого среза (п.11 дизайн-документа).
 * Работа даёт деньги и медленную практику; быстрый рост — только через учёбу.
 */
export const JOBS: readonly JobDef[] = [
  // --- год в деревне (этап 67, Я1): весной сеют, осенью жнут, и обе работы
  // бывают только в свой срок. Платят за них лучше обычного — потому что
  // руки нужны сейчас, а не вообще.
  {
    id: 'sowField',
    openHands: true,
    where: {
      archetypes: ['village', 'town'],
      seasons: ['spring'],
    },
    label: 'Выйти на сев',
    description:
      'Борона, лукошко и вся деревня в поле от света до света. Опоздавшим не сеют — им потом не жнут.',
    durationMinutes: hours(10),
    pay: 15,
    practice: { hardLabour: 26, survival: 10 },
    fatigue: 38,
  },
  {
    id: 'reapField',
    openHands: true,
    where: {
      archetypes: ['village', 'town'],
      seasons: ['autumn'],
    },
    label: 'Выйти на жатву',
    description:
      'Серп, спина и страх перед дождём. В эти три недели в деревне платят всем, кто держится на ногах.',
    durationMinutes: hours(11),
    pay: 20,
    practice: { hardLabour: 30, fortitude: 10 },
    fatigue: 44,
  },
  {
    id: 'winterYard',
    openHands: true,
    where: {
      archetypes: ['village', 'town', 'city', 'capital', 'port', 'fortress', 'mine'],
      seasons: ['winter'],
    },
    label: 'Зимняя подёнщина',
    description:
      'Чистить снег, колоть дрова, возить воду. Работа не велика, но зимой другой и нет.',
    durationMinutes: hours(6),
    pay: 7,
    practice: { hardLabour: 14, fortitude: 6 },
    fatigue: 22,
  },
  // --- ремесло по земле (этап 50, М5): что делают под горой, не делают в порту
  {
    id: 'breakOre',
    where: { archetypes: ['mine', 'fortress'], terrains: ['mountains', 'hills'] },
    label: 'Бить руду',
    description: 'Кайло, штольня и порода, которая не хочет отдавать железо. Платят по весу.',
    durationMinutes: hours(9),
    pay: 16,
    practice: { hardLabour: 30, fortitude: 8 },
    fatigue: 40,
  },
  {
    id: 'tarRigging',
    where: { archetypes: ['port'] },
    label: 'Смолить снасти',
    description: 'Канаты, смола и руки, которые потом три дня пахнут. Зато шкиперы запоминают.',
    durationMinutes: hours(7),
    pay: 14,
    practice: { hardLabour: 18, engineering: 14 },
    fatigue: 30,
  },
  {
    id: 'burnPitch',
    where: { terrains: ['forest'] },
    label: 'Гнать дёготь',
    description: 'Яма, береста и дым, от которого слезятся глаза. Дёготь берут все, кто с телегой.',
    durationMinutes: hours(8),
    pay: 13,
    practice: { survival: 16, engineering: 12 },
    fatigue: 32,
  },
  {
    id: 'tanHides',
    where: { archetypes: TOWNS, minPopulation: 1500 },
    label: 'Дубить кожу',
    description: 'Чаны, известь и запах, из-за которого дубильни ставят за околицей.',
    durationMinutes: hours(8),
    pay: 15,
    practice: { hardLabour: 16, sleight: 16 },
    fatigue: 30,
  },
  {
    id: 'cutSalt',
    where: { terrains: ['desert', 'coast'] },
    label: 'Резать соль',
    description: 'Солончак под солнцем: режут плитами, носят на спине, считают на вес серебра.',
    durationMinutes: hours(9),
    pay: 17,
    practice: { hardLabour: 24, fortitude: 12 },
    fatigue: 42,
  },
  {
    id: 'feltWool',
    where: { terrains: ['steppe', 'hills'] },
    label: 'Валять шерсть',
    description: 'Шерсть, горячая вода и час за часом одно движение. Войлок кормит всю степь.',
    durationMinutes: hours(7),
    pay: 11,
    practice: { sleight: 20, hardLabour: 10 },
    fatigue: 26,
  },
  {
    id: 'unloadCarts',
    where: { archetypes: TOWNS, minPopulation: 1000 },
    label: 'Разгружать телеги',
    description: 'Купцам всегда нужны руки у складских ворот. Спину жалеть не станут.',
    durationMinutes: hours(8),
    pay: 12,
    practice: { hardLabour: 26, athletics: 8 },
    fatigue: 35,
  },
  {
    id: 'muckStables',
    label: 'Чистить конюшни',
    description: 'Работа, которой не хвастаются. Зато лошадей узнаёшь быстро.',
    durationMinutes: hours(6),
    pay: 7,
    practice: { hardLabour: 14, riding: 10 },
    fatigue: 25,
  },
  {
    id: 'runErrands',
    where: { archetypes: TOWNS },
    label: 'Бегать с поручениями',
    description: 'Отнести, договориться, вернуться с ответом. Полгорода за полдня.',
    durationMinutes: hours(4),
    pay: 5,
    practice: { persuasion: 14, athletics: 6 },
    fatigue: 15,
  },
  {
    id: 'gatherHerbs',
    where: { archetypes: ['village', 'town', 'fortress', 'monastery', 'mine', 'port'] },
    label: 'Собирать травы за стенами',
    description: 'Лекарь платит за корзину. За стенами города бывает по-разному.',
    durationMinutes: hours(6),
    pay: 9,
    practice: { survival: 20, healing: 10 },
    fatigue: 20,
  },
  {
    id: 'copyPapers',
    where: { archetypes: ['city', 'capital', 'monastery'] },
    label: 'Переписывать бумаги',
    description: 'Писцу нужна вторая рука. Платят не за скорость, а за отсутствие ошибок.',
    durationMinutes: hours(6),
    pay: 14,
    practice: { scholarship: 22 },
    fatigue: 10,
    requires: { skills: { scholarship: 5 } },
  },
  {
    id: 'serveAtSchool',
    where: { archetypes: ['capital'] },
    label: 'Прислуживать в школе магии',
    description: 'Платят гроши, но ты внутри стен, и до чужих занятий два шага.',
    durationMinutes: hours(6),
    pay: 6,
    practice: { concentration: 14, scholarship: 10 },
    fatigue: 15,
    // Со стороны в школу не берут: нужен кто-то, кто тебя там уже знает.
    requires: { tags: ['school_known'] },
  },
  // --- магия за плату (этап 41): маг зарабатывает ремеслом, а не рангом -------
  {
    id: 'charmCattle',
    where: { archetypes: ['village', 'town'] },
    label: 'Заговаривать скот',
    description:
      'Хозяева ведут коров и лошадей: от сглаза, от хромоты, от волка. Платят молоком и медью.',
    durationMinutes: hours(4),
    pay: 18,
    practice: { magic: 16, concentration: 8 },
    fatigue: 22,
    requires: { skills: { magic: 12 } },
  },
  {
    id: 'layHands',
    where: { archetypes: TOWNS },
    label: 'Лечить наложением рук',
    description: 'Очередь с утра: зубы, спины, младенцы. Не всех вылечишь, но всем полегчает.',
    durationMinutes: hours(5),
    pay: 40,
    practice: { magic: 24, healing: 12 },
    fatigue: 35,
    requires: { skills: { magic: 30 } },
  },
  {
    id: 'wardGranary',
    where: { archetypes: ['city', 'capital', 'port'] },
    label: 'Ставить обереги на склады',
    description: 'Купцы платят за то, чтобы не сырело, не горело и не воровалось. Дорого и на год.',
    durationMinutes: hours(6),
    pay: 90,
    practice: { magic: 30, scholarship: 10 },
    fatigue: 40,
    requires: { skills: { magic: 50 } },
  },
  {
    id: 'guardCaravan',
    where: { archetypes: TOWNS, minPopulation: 1500 },
    label: 'Охранять караван',
    description: 'Сутки при оружии на дороге. Лучшая плата из доступных новичку.',
    durationMinutes: hours(12),
    pay: 30,
    practice: { lightWeapons: 24, archery: 10, riding: 8, fortitude: 6 },
    fatigue: 45,
    requires: { skills: { lightWeapons: 5 } },
  },
  {
    id: 'tavernHand',
    where: { archetypes: TOWNS },
    label: 'Подавать в таверне',
    description: 'Шум, чужие ссоры и монета за вечер. Языком работаешь не меньше, чем руками.',
    durationMinutes: hours(5),
    pay: 8,
    practice: { persuasion: 16, trade: 8 },
    fatigue: 18,
    window: { fromHour: 16, toHour: 24 },
  },
  {
    id: 'nightWatch',
    where: { archetypes: ['town', 'city', 'capital', 'port', 'fortress'] },
    label: 'Ночной сторож',
    description: 'Обходить склады до рассвета. Платят за бессонницу, а не за храбрость.',
    durationMinutes: hours(8),
    pay: 15,
    practice: { fortitude: 16, lightWeapons: 8 },
    fatigue: 40,
    window: NIGHT_WINDOW,
  },
  {
    id: 'huntGame',
    where: {
      archetypes: ['village', 'fortress', 'monastery', 'mine'],
      terrains: ['forest', 'hills', 'steppe', 'mountains', 'marsh'],
    },
    label: 'Бить дичь на продажу',
    description: 'Лес кормит того, кто умеет ждать. Мясник берёт всё, о чём не спрашивает.',
    durationMinutes: hours(9),
    pay: 18,
    practice: { archery: 26, survival: 14 },
    fatigue: 35,
    requires: { skills: { archery: 8 } },
  },
  {
    id: 'healerHand',
    where: { archetypes: ['town', 'city', 'capital', 'monastery'] },
    label: 'Помогать лекарю',
    description: 'Держать, перевязывать и не падать в обморок. Учит быстрее, чем хотелось бы.',
    durationMinutes: hours(7),
    pay: 13,
    practice: { healing: 26, scholarship: 6 },
    fatigue: 22,
    requires: { skills: { healing: 6 } },
  },
  {
    id: 'quarryShift',
    where: { archetypes: ['mine'] },
    label: 'Смена в каменоломне',
    description: 'Камень, пыль и десятник, который считает вынутые корзины, а не людей.',
    durationMinutes: hours(10),
    pay: 22,
    practice: { hardLabour: 30, athletics: 12, fortitude: 6 },
    fatigue: 55,
    requires: { skills: { hardLabour: 10 } },
  },
  {
    id: 'countLedgers',
    where: { archetypes: ['city', 'capital', 'port'] },
    label: 'Считать чужие долги',
    description: 'Купеческие книги. Ошибёшься в свою пользу — заметят; в чужую — не заметят.',
    durationMinutes: hours(6),
    pay: 24,
    practice: { trade: 22, scholarship: 12 },
    fatigue: 12,
    requires: { skills: { trade: 10, scholarship: 8 } },
  },
  {
    id: 'fieldWork',
    label: 'Работа в поле',
    description: 'Сев, жатва, прополка — смотря какой месяц. Спина не спрашивает.',
    where: { archetypes: ['village', 'town'], terrains: ['plains', 'steppe', 'coast', 'hills'] },
    durationMinutes: hours(9),
    pay: 6,
    practice: { hardLabour: 22, survival: 8 },
    fatigue: 38,
  },
  {
    id: 'haulNets',
    label: 'Тянуть сети',
    description: 'Холодная вода до пояса и улов, который делят прежде тебя.',
    where: { archetypes: ['port', 'village'], terrains: ['coast', 'marsh'] },
    durationMinutes: hours(7),
    pay: 10,
    practice: { hardLabour: 16, survival: 14, athletics: 8 },
    fatigue: 32,
  },
  {
    id: 'loadShips',
    label: 'Грузить корабли',
    description: 'Сходни, мешки и боцман, который считает время в мешках.',
    where: { archetypes: ['port'] },
    durationMinutes: hours(8),
    pay: 16,
    practice: { hardLabour: 26, athletics: 10 },
    fatigue: 42,
    requires: { skills: { hardLabour: 5 } },
  },
  {
    id: 'washOre',
    label: 'Промывать руду',
    description: 'Сидеть над корытом и выбирать блеск из грязи. Берут кого угодно.',
    where: { archetypes: ['mine'] },
    durationMinutes: hours(7),
    pay: 9,
    practice: { hardLabour: 14, engineering: 10 },
    fatigue: 24,
  },
  {
    id: 'standWatch',
    label: 'Стоять в карауле',
    description: 'Стена, ветер и десятник, который проверяет, не спишь ли ты стоя.',
    where: { archetypes: ['fortress'] },
    durationMinutes: hours(10),
    pay: 11,
    practice: { fortitude: 18, lightWeapons: 12, heavyWeapons: 6 },
    fatigue: 36,
  },
  {
    id: 'copyPsalter',
    label: 'Переписывать псалтырь',
    description: 'Обитель кормит и даёт кров, а платит скупо и с укором.',
    where: { archetypes: ['monastery'] },
    durationMinutes: hours(8),
    pay: 8,
    practice: { scholarship: 24, concentration: 10 },
    fatigue: 14,
    requires: { skills: { scholarship: 3 } },
  },

  // --- вторая половина: по всем навыкам и по всем видам мест -----------------
  {
    id: 'splitFirewood',
    label: 'Колоть дрова',
    description: 'Зима не спрашивает. Колун тяжёлый, поленница — длинная.',
    durationMinutes: hours(6),
    pay: 6,
    practice: { hardLabour: 20, athletics: 6 },
    fatigue: 30,
  },
  {
    id: 'shoeHorses',
    where: { archetypes: ['village', 'town', 'fortress'] },
    label: 'Держать лошадь у кузнеца',
    description: 'Кузнец куёт, ты держишь. Лошадь не согласна с обоими.',
    durationMinutes: hours(5),
    pay: 8,
    practice: { riding: 14, fortitude: 8 },
    fatigue: 22,
  },
  {
    id: 'sellAtMarket',
    where: { archetypes: TOWNS },
    label: 'Стоять за прилавком',
    description: 'Купцу нужен человек, который умеет считать сдачу и не хамить. Второе труднее.',
    durationMinutes: hours(8),
    pay: 9,
    practice: { trade: 22, persuasion: 8 },
    fatigue: 18,
    requires: { skills: { trade: 3 } },
  },
  {
    id: 'readLetters',
    where: { archetypes: ['village', 'town', 'monastery'] },
    label: 'Читать письма неграмотным',
    description:
      'Полдеревни ждёт вестей, и ни один не умеет их прочесть. Платят яйцами, но и монетами тоже.',
    durationMinutes: hours(3),
    pay: 4,
    practice: { scholarship: 14, persuasion: 6 },
    fatigue: 6,
    requires: { tags: ['literate'] },
  },
  {
    id: 'drillMilitia',
    where: { archetypes: ['village', 'town', 'fortress'] },
    label: 'Гонять ополчение',
    description: 'Мужики с копьями, которые держат их как вилы. Из них надо сделать строй.',
    durationMinutes: hours(6),
    pay: 14,
    practice: { command: 24, heavyWeapons: 8 },
    fatigue: 25,
    requires: { skills: { command: 4 } },
  },
  {
    id: 'sparBarracks',
    where: { archetypes: ['fortress', 'capital', 'city'] },
    label: 'Стоять спарринг-партнёром',
    description: 'Стражу надо на ком-то учить. Синяки — твои, серебро — тоже твоё.',
    durationMinutes: hours(4),
    pay: 11,
    practice: { heavyWeapons: 18, fortitude: 12 },
    fatigue: 30,
  },
  {
    id: 'pickPockets',
    where: { archetypes: ['city', 'capital', 'port'], minPopulation: 2000 },
    label: 'Работать по карманам',
    description: 'Толпа на площади, чужой кошель и одна секунда. Платит толпа, ловит стража.',
    durationMinutes: hours(3),
    pay: 16,
    practice: { sleight: 24, athletics: 6 },
    fatigue: 15,
    requires: { skills: { sleight: 5 } },
    window: { fromHour: 10, toHour: 16 },
  },
  {
    id: 'repairBridge',
    where: { archetypes: ['village', 'town'], terrains: ['forest', 'marsh', 'hills'] },
    label: 'Чинить мост',
    description: 'Мост держится на честном слове и двух брёвнах. Одно из них — гнилое.',
    durationMinutes: hours(7),
    pay: 13,
    practice: { engineering: 20, hardLabour: 12 },
    fatigue: 30,
    requires: { skills: { engineering: 3 } },
  },
  {
    id: 'digWell',
    where: { archetypes: ['village'], terrains: ['plains', 'steppe', 'hills'] },
    label: 'Рыть колодец',
    description: 'Три сажени вниз, вода — не обещана. Платят за глубину, а не за воду.',
    durationMinutes: hours(8),
    pay: 10,
    practice: { hardLabour: 22, engineering: 8 },
    fatigue: 38,
  },
  {
    id: 'ferryCrossing',
    where: { archetypes: ['village', 'town', 'port'], terrains: ['coast', 'marsh'] },
    label: 'Ходить на пароме',
    description: 'Шест, течение и телега с быком, который не хочет на тот берег.',
    durationMinutes: hours(6),
    pay: 8,
    practice: { athletics: 18, hardLabour: 10 },
    fatigue: 28,
  },
  {
    id: 'guideTravellers',
    where: {
      archetypes: ['village', 'mine', 'fortress'],
      terrains: ['mountains', 'hills', 'forest'],
    },
    label: 'Водить через перевал',
    description: 'Купцы платят за то, чтобы прийти, а не за дорогу. Дорогу знаешь ты.',
    durationMinutes: hours(9),
    pay: 17,
    practice: { survival: 22, athletics: 10 },
    fatigue: 32,
    requires: { skills: { survival: 6 } },
  },
  {
    id: 'lightLamps',
    where: { archetypes: ['city', 'capital'] },
    label: 'Зажигать фонари',
    description: 'Сто фонарей, одна лестница, одна ночь. К утру — ещё сто, чтобы погасить.',
    durationMinutes: hours(4),
    pay: 5,
    practice: { athletics: 12, concentration: 6 },
    fatigue: 15,
    window: NIGHT_WINDOW,
  },
  {
    id: 'sitWithDying',
    where: { archetypes: ['monastery', 'city', 'capital'] },
    label: 'Сидеть с умирающими',
    description: 'Лечебница платит тем, кто не боится. Первую ночь — боятся все.',
    durationMinutes: hours(8),
    pay: 7,
    practice: { healing: 16, fortitude: 12 },
    fatigue: 20,
    window: NIGHT_WINDOW,
  },
  {
    id: 'chantForCoin',
    where: { archetypes: ['monastery', 'town'] },
    label: 'Читать молитвы на заказ',
    description: 'За упокой, за здравие, за урожай. Голос нужен ровный, вера — на твоё усмотрение.',
    durationMinutes: hours(3),
    pay: 5,
    practice: { concentration: 16, persuasion: 6 },
    fatigue: 8,
    requires: { skills: { concentration: 3 } },
  },
  {
    id: 'escortTaxes',
    where: { archetypes: ['town', 'city', 'capital'] },
    label: 'Сопровождать сборщика',
    description: 'Сборщик податей нигде не любим, а деньги при нём — любимы всеми. Идёшь рядом.',
    durationMinutes: hours(8),
    pay: 20,
    practice: { lightWeapons: 16, persuasion: 10, riding: 6 },
    fatigue: 28,
    requires: { skills: { lightWeapons: 6 } },
  },
  {
    id: 'sortOre',
    where: { archetypes: ['mine'] },
    label: 'Разбирать руду',
    description: 'Пустая порода налево, руда направо. К вечеру перестаёшь различать.',
    durationMinutes: hours(7),
    pay: 8,
    practice: { concentration: 12, hardLabour: 10 },
    fatigue: 24,
  },
  {
    id: 'mendNets',
    where: { archetypes: ['port', 'village'], terrains: ['coast', 'marsh'] },
    label: 'Чинить сети',
    description: 'Узел за узлом, весь день на берегу. Руки в соли, спина — в узлах.',
    durationMinutes: hours(6),
    pay: 5,
    practice: { sleight: 12, concentration: 8 },
    fatigue: 14,
  },
  {
    id: 'tameHorses',
    where: { archetypes: ['village', 'town'], terrains: ['steppe', 'plains'] },
    label: 'Объезжать лошадей',
    description: 'Дикую — в седло, а тебя — из седла. Кто дольше, тот и прав.',
    durationMinutes: hours(6),
    pay: 15,
    practice: { riding: 26, fortitude: 10 },
    fatigue: 35,
    requires: { skills: { riding: 8 } },
  },
  {
    id: 'castWards',
    where: { archetypes: ['village', 'town'] },
    label: 'Ставить обереги на дом',
    description: 'Хозяйка верит, что ты умеешь. Ты — тоже, но меньше.',
    durationMinutes: hours(3),
    pay: 12,
    practice: { magic: 14, persuasion: 8 },
    fatigue: 14,
    requires: { skills: { magic: 5 } },
  },
  {
    id: 'shootAtFair',
    where: { archetypes: ['town', 'city'] },
    label: 'Стрелять на ярмарке',
    description: 'Приз за десять из десяти. Хозяин балагана ставит на то, что ты промахнёшься.',
    durationMinutes: hours(4),
    pay: 14,
    practice: { archery: 20, concentration: 6 },
    fatigue: 15,
    requires: { skills: { archery: 6 } },
  },
  {
    id: 'carryWounded',
    where: { archetypes: ['fortress', 'capital'] },
    label: 'Носить раненых',
    description: 'После учений или после боя — носилки те же. Лекарь показывает, кого первым.',
    durationMinutes: hours(6),
    pay: 9,
    practice: { healing: 12, hardLabour: 12, fortitude: 6 },
    fatigue: 26,
  },

  // --- работа земли: это делают там, где людей не живёт -----------------------
  {
    id: 'trapFurs',
    where: { archetypes: ['grove', 'wilds'] },
    label: 'Ставить силки',
    description: 'Обойти петли с вечера и с утра. Что попалось — твоё, что ушло — не твоё.',
    durationMinutes: hours(7),
    pay: 11,
    practice: { survival: 24, sleight: 8 },
    fatigue: 26,
  },
  {
    id: 'gatherWild',
    where: { archetypes: ['grove', 'spring', 'wilds', 'causeway'] },
    label: 'Собирать, что растёт',
    description: 'Травы, кора, ягода. Лекарь в городе берёт, не спрашивая, где взял.',
    durationMinutes: hours(5),
    pay: 7,
    practice: { survival: 18, healing: 8 },
    fatigue: 18,
  },
  {
    id: 'netFord',
    where: { archetypes: ['ford', 'crossing'] },
    label: 'Ставить сети на перекате',
    description: 'Рыба идёт мелким местом. Ноги мокрые, зато к вечеру полная корзина.',
    durationMinutes: hours(6),
    pay: 9,
    practice: { survival: 14, athletics: 10 },
    fatigue: 22,
  },
  {
    id: 'breakStone',
    where: { archetypes: ['quarry'] },
    label: 'Бить камень',
    description: 'Кайло, клин и день без тени. Платят с воза, а не с часа.',
    durationMinutes: hours(8),
    pay: 13,
    practice: { hardLabour: 26, fortitude: 8 },
    fatigue: 40,
  },
  {
    id: 'mendCauseway',
    where: { archetypes: ['causeway'] },
    label: 'Чинить гать',
    description: 'Брёвна кладут поперёк и каждый год заново: топь берёт своё.',
    durationMinutes: hours(7),
    pay: 12,
    practice: { hardLabour: 20, engineering: 10 },
    fatigue: 34,
  },
  {
    id: 'standGate',
    where: { archetypes: ['outpost'] },
    label: 'Стоять на заставе',
    description: 'Досматривать подводы, спрашивать имя, брать с каждого второго.',
    durationMinutes: hours(8),
    pay: 14,
    practice: { persuasion: 16, lightWeapons: 10, fortitude: 6 },
    fatigue: 20,
  },
  {
    id: 'guideOverPass',
    where: { archetypes: ['pass'] },
    label: 'Провести обоз через перевал',
    description: 'Купцы платят за то, чтобы дойти. Дорогу знаешь ты, а не они.',
    durationMinutes: hours(9),
    pay: 22,
    practice: { survival: 24, riding: 10, athletics: 8 },
    fatigue: 38,
    requires: { skills: { survival: 6 } },
  },
  {
    id: 'keepVigil',
    where: { archetypes: ['shrine', 'barrow'] },
    label: 'Сторожить ночь',
    description: 'Проезжие платят, чтобы кто-то не спал у огня, пока спят они.',
    durationMinutes: hours(6),
    pay: 8,
    practice: { concentration: 18, fortitude: 10 },
    fatigue: 16,
    window: NIGHT_WINDOW,
  },
]

export const JOBS_BY_ID: Readonly<Record<string, JobDef>> = Object.fromEntries(
  JOBS.map((job) => [job.id, job]),
)
